#include <dace/dace.h>
typedef void *cloudsc_pyHandle_t;
extern "C" cloudsc_pyHandle_t __dace_init_cloudsc_py(int klev, int klon,
                                                     int ncldqi, int ncldql,
                                                     int ncldqr, int ncldqs,
                                                     int ncldqv, int nclv);
extern "C" int __dace_exit_cloudsc_py(cloudsc_pyHandle_t handle);
extern "C" void __program_cloudsc_py(
    cloudsc_pyHandle_t handle, int *__restrict__ ktype, int *__restrict__ ldcum,
    double *__restrict__ pa, double *__restrict__ pap,
    double *__restrict__ paph, double *__restrict__ pccn,
    double *__restrict__ pclv, double *__restrict__ pcovptot,
    double *__restrict__ pdyna, double *__restrict__ pdyni,
    double *__restrict__ pdynl, double *__restrict__ pfcqlng,
    double *__restrict__ pfcqnng, double *__restrict__ pfcqrng,
    double *__restrict__ pfcqsng, double *__restrict__ pfhpsl,
    double *__restrict__ pfhpsn, double *__restrict__ pfplsl,
    double *__restrict__ pfplsn, double *__restrict__ pfsqif,
    double *__restrict__ pfsqitur, double *__restrict__ pfsqlf,
    double *__restrict__ pfsqltur, double *__restrict__ pfsqrf,
    double *__restrict__ pfsqsf, double *__restrict__ phrlw,
    double *__restrict__ phrsw, double *__restrict__ picrit_aer,
    double *__restrict__ plcrit_aer, double *__restrict__ plsm,
    double *__restrict__ plu, double *__restrict__ plude,
    double *__restrict__ pmfd, double *__restrict__ pmfu,
    double *__restrict__ pnice, double *__restrict__ pq,
    double *__restrict__ prainfrac_toprfz, double *__restrict__ pre_ice,
    double *__restrict__ psnde, double *__restrict__ psupsat,
    double *__restrict__ pt, double *__restrict__ pvervel,
    double *__restrict__ pvfa, double *__restrict__ pvfi,
    double *__restrict__ pvfl, double *__restrict__ tendency_loc_a,
    double *__restrict__ tendency_loc_cld, double *__restrict__ tendency_loc_q,
    double *__restrict__ tendency_loc_t, double *__restrict__ tendency_tmp_a,
    double *__restrict__ tendency_tmp_cld, double *__restrict__ tendency_tmp_q,
    double *__restrict__ tendency_tmp_t, int kfdia, int kidia, int klev,
    int klon, int ncldqi, int ncldql, int ncldqr, int ncldqs, int ncldqv,
    int nclv, double ptsphy, double ydcst_rcpd, double ydcst_rd,
    double ydcst_retv, double ydcst_rg, double ydcst_rlmlt, double ydcst_rlstt,
    double ydcst_rlvtt, double ydcst_rtt, double ydcst_rv, double ydthf_r2es,
    double ydthf_r3ies, double ydthf_r3les, double ydthf_r4ies,
    double ydthf_r4les, double ydthf_r5alscp, double ydthf_r5alvcp,
    double ydthf_r5ies, double ydthf_r5les, double ydthf_ralfdcp,
    double ydthf_ralsdcp, double ydthf_ralvdcp, double ydthf_rkoop1,
    double ydthf_rkoop2, double ydthf_rtice, double ydthf_rticecu,
    double ydthf_rtwat, double ydthf_rtwat_rtice_r,
    double ydthf_rtwat_rticecu_r, int yrecldp_laericeauto,
    int yrecldp_laericesed, int yrecldp_laerliqautolsp, int yrecldp_laerliqcoll,
    int yrecldp_ncldtop, int yrecldp_nssopt, double yrecldp_ramid,
    double yrecldp_ramin, double yrecldp_rccn, double yrecldp_rcl_apb1,
    double yrecldp_rcl_apb2, double yrecldp_rcl_apb3,
    double yrecldp_rcl_cdenom1, double yrecldp_rcl_cdenom2,
    double yrecldp_rcl_cdenom3, double yrecldp_rcl_const1i,
    double yrecldp_rcl_const1r, double yrecldp_rcl_const1s,
    double yrecldp_rcl_const2i, double yrecldp_rcl_const2r,
    double yrecldp_rcl_const2s, double yrecldp_rcl_const3i,
    double yrecldp_rcl_const3r, double yrecldp_rcl_const3s,
    double yrecldp_rcl_const4i, double yrecldp_rcl_const4r,
    double yrecldp_rcl_const4s, double yrecldp_rcl_const5i,
    double yrecldp_rcl_const5r, double yrecldp_rcl_const5s,
    double yrecldp_rcl_const6i, double yrecldp_rcl_const6r,
    double yrecldp_rcl_const6s, double yrecldp_rcl_const7s,
    double yrecldp_rcl_const8s, double yrecldp_rcl_fac1,
    double yrecldp_rcl_fac2, double yrecldp_rcl_fzrab, double yrecldp_rcl_ka273,
    double yrecldp_rcl_kk_cloud_num_land, double yrecldp_rcl_kk_cloud_num_sea,
    double yrecldp_rcl_kkaac, double yrecldp_rcl_kkaau,
    double yrecldp_rcl_kkbac, double yrecldp_rcl_kkbaun,
    double yrecldp_rcl_kkbauq, double yrecldp_rclcrit_land,
    double yrecldp_rclcrit_sea, double yrecldp_rcldiff,
    double yrecldp_rcldiff_convi, double yrecldp_rcldtopcf,
    double yrecldp_rcovpmin, double yrecldp_rdensref,
    double yrecldp_rdepliqrefdepth, double yrecldp_rdepliqrefrate,
    double yrecldp_riceinit, double yrecldp_rkconv, double yrecldp_rkooptau,
    double yrecldp_rlcritsnow, double yrecldp_rlmin, double yrecldp_rnice,
    double yrecldp_rpecons, double yrecldp_rprc1, double yrecldp_rprecrhmax,
    double yrecldp_rsnowlin1, double yrecldp_rsnowlin2, double yrecldp_rtaumel,
    double yrecldp_rthomo, double yrecldp_rvice, double yrecldp_rvrain,
    double yrecldp_rvrfactor, double yrecldp_rvsnow);
