#!/bin/sh
set -e
BINARY=libvelocity_gpu_stage8_solve_nh_integration_release.f16.so

nvcc codegen/stage8/f16/velocity_no_nproma_if_prop_lvn_only_0_istep_1_cuda.cu codegen/stage8/f16/velocity_no_nproma_if_prop_lvn_only_0_istep_2.cu codegen/stage8/f16/velocity_no_nproma_if_prop_lvn_only_1_istep_2.cu codegen/stage8/f16/velocity_no_nproma_if_prop_lvn_only_1_istep_2_cuda.cu codegen/stage8/f16/velocity_no_nproma_if_prop_lvn_only_0_istep_1.cu codegen/stage8/f16/velocity_no_nproma_if_prop_lvn_only_0_istep_2_cuda.cu src/reductions_kernel.cu codegen/stage8/f16/velocity_no_nproma_if_prop_lvn_only_1_istep_1.cu src/gpu_mem.cpp codegen/stage8/f16/velocity_no_nproma_if_prop_lvn_only_1_istep_1_cuda.cu src/timer.cpp src/reductions.cpp src/sqlite_logger.cpp -Icodegen/stage8/f16 -I/Users/pmz/gitspace/ico2/dace/dace/runtime/include/ -Iinclude   -I/opt/homebrew/opt/zstd/include  --diag-suppress 68 --diag-suppress 550 --diag-suppress 20208 --diag-suppress 1835 --diag-suppress 177 --diag-suppress 20012 --diag-suppress 1098 -Xcompiler=-Wall -Xcompiler=-Wextra -Xcompiler=-Wno-unused-parameter -Xcompiler=-Wconversion -Xcompiler=-Wno-sign-conversion -Xcompiler=-Wfloat-conversion -Xcompiler=-Wno-unknown-pragmas -Xcompiler=-faligned-new -DNDEBUG -Xcompiler=-DNDEBUG -Xcompiler=-O3 --expt-relaxed-constexpr -gencode arch=compute_90,code=sm_90 --use_fast_math -O3 -lineinfo --ftz=true --prec-div=false --prec-sqrt=false --fmad=true -Xptxas=-O3 -Xptxas=-v -Xcompiler=-march=native -Xcompiler=-mtune=native --restrict -DNDEBUG -DNO_SERDE -DNVTX_DISABLE -std=c++17 -Xcompiler=-fPIC --compiler-options '-fPIC' --shared -Xlinker --wrap=cudaMalloc -Xlinker --wrap=cudaFree --keep --keep-dir=ptx_out/f16 -DLOWPREC_TAG=\"f16\"  -lsqlite3 -lz -L/opt/homebrew/opt/zstd/lib -lzstd -lsqlite3 -lz -lzstd -o libvelocity_gpu_stage8_solve_nh_integration_release.f16.so

# Dump SASS (native assembly) alongside PTX
echo "Dumping SASS to ptx_out/f16/ ..."
cuobjdump -sass "$BINARY" > ptx_out/f16/all_kernels.sass
